### ISSUE TITLE
Add py.typed file so that type hints are readable in mypy

### ISSUE THREAD

**Issue by mtvx** [marverix/casey#2]
Else users get error like:

    env/wires/env/core.py:12:1: error: Cannot find implementation or library stub for module named 'casey'  [import]
    env/wires/env/core.py:12:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports

See https://www.python.org/dev/peps/pep-0561.

**Comment by marverix** [comment]
Hey @tuukkamustonen , thanks for the hint! I'm still learning Python so it's nice that you pointed me this one. I will try to add it ASAP :)

**Comment by marverix** [comment]
@tuukkamustonen I have released version 1.0.2. Can you confirm if this resolves the issue? Thanks

**Comment by mtvx** [comment]
Unfortunately no. `py.typed` is not included in the packages: https://pypi.org/project/casey/1.0.2/#files

You should explicitly tell `poetry` to include it, I guess something like this: https://python-poetry.org/docs/pyproject/#include-and-exclude (but I don't personally use poetry so dunno).

**Comment by marverix** [comment]
Ok, now should be ok. `py.typed` must be in the module directory, not in the repo root directory, and then poetry will include it automatically. Please verify version 1.0.3

**Comment by mtvx** [comment]
Hi, I'm having a few days off so can't be really testing it, but the package indeed seems to contain the file now. So I believe this is resolved and can be closed. Thanks!
